### ISSUE TITLE
[Class definition not found] while running token example

### ISSUE THREAD

**Issue by scucchiero** [corda/cordapp-template-kotlin#71]
Running nodes w/ token example cordapp fails while booting.

**Error**
`
[quasar] WARNING: Method not found in class - assuming suspendable: com/r3/corda/lib/tokens/selection/api/Selector#generateMove$default(Lcom/r3/corda/lib/tokens/selection/api/Selector;Ljava/util/List;Lnet/corda/core/identity/AbstractParty;Lcom/r3/corda/lib/tokens/selection/TokenQueryBy;Ljava/util/UUID;ILjava/lang/Object;)Lkotlin/Pair; (at TestFlows.kt:com/r3/corda/lib/tokens/workflows/internal/testflows/DvPFlowHandler#call)
[quasar] WARNING: Method not found in class - assuming suspendable: com/r3/corda/lib/tokens/testing/states/House#getValuation()Lnet/corda/core/contracts/Amount; (at TestFlows.kt:com/r3/corda/lib/tokens/workflows/internal/testflows/DvPFlow#call)
[quasar] WARNING: Method not found in class - assuming suspendable: com/r3/corda/lib/tokens/selection/api/Selector#selectTokens$default(Lcom/r3/corda/lib/tokens/selection/api/Selector;Lnet/corda/core/contracts/Amount;Lcom/r3/corda/lib/tokens/selection/TokenQueryBy;Ljava/util/UUID;ILjava/lang/Object;)Ljava/util/List; (at TestFlows.kt:com/r3/corda/lib/tokens/workflows/internal/testflows/SelectAndLockFlow#call)
[quasar] WARNING: Method not found in class - assuming suspendable: com/r3/corda/lib/tokens/selection/database/selector/DatabaseTokenSelection#generateMove(Ljava/util/List;Lnet/corda/core/identity/AbstractParty;Lcom/r3/corda/lib/tokens/selection/TokenQueryBy;Ljava/util/UUID;)Lkotlin/Pair; (at ConfidentialMoveFungibleTokensFlow.kt:com/r3/corda/lib/tokens/workflows/flows/move/ConfidentialMoveFungibleTokensFlow#call)
! ATTENTION: This node is running in development mode!  This is not safe for production deployment.
Exception in thread "main" java.lang.NoClassDefFoundError: com/r3/corda/lib/tokens/selection/api/Selector
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getDeclaredConstructors(Class.java:2020)
        at net.corda.node.internal.NodeFlowManager.registerInitiatedFlow(FlowManager.kt:77)
        at net.corda.node.internal.AbstractNode$registerCordappFlows$$inlined$forEach$lambda$1.accept(AbstractNode.kt:727)
        at net.corda.node.internal.AbstractNode$registerCordappFlows$$inlined$forEach$lambda$1.accept(AbstractNode.kt:122)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at net.corda.node.internal.AbstractNode.registerCordappFlows(AbstractNode.kt:724)
        at net.corda.node.internal.AbstractNode.start(AbstractNode.kt:344)
        at net.corda.node.internal.Node.start(Node.kt:447)
        at net.corda.node.internal.NodeStartup.startNode(NodeStartup.kt:210)
        at net.corda.node.internal.NodeStartupCli$runProgram$2.run(NodeStartup.kt:131)
        at net.corda.node.internal.NodeStartup$initialiseAndRun$5.invoke(NodeStartup.kt:187)
        at net.corda.node.internal.NodeStartup$initialiseAndRun$5.invoke(NodeStartup.kt:138)
        at net.corda.node.internal.NodeStartupLogging$DefaultImpls.attempt(NodeStartup.kt:529)
        at net.corda.node.internal.NodeStartup.attempt(NodeStartup.kt:138)
        at net.corda.node.internal.NodeStartup.initialiseAndRun(NodeStartup.kt:186)
        at net.corda.node.internal.NodeStartupCli.runProgram(NodeStartup.kt:129)
        at net.corda.cliutils.CordaCliWrapper.call(CordaCliWrapper.kt:190)
        at net.corda.node.internal.NodeStartupCli.call(NodeStartup.kt:84)
        at net.corda.node.internal.NodeStartupCli.call(NodeStartup.kt:65)
        at picocli.CommandLine.execute(CommandLine.java:1173)
        at picocli.CommandLine.access$800(CommandLine.java:141)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1367)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1335)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
        at net.corda.cliutils.CordaCliWrapperKt.start(CordaCliWrapper.kt:73)
        at net.corda.node.Corda.main(Corda.kt:13)
Caused by: java.lang.ClassNotFoundException: com.r3.corda.lib.tokens.selection.api.Selector
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        ... 29 more
[ERROR] 22:45:43-0300 [main] internal.GeneralExceptionHandler. - Exception in thread "main" [errorCode=1gnp94c, moreInformationAt=https://errors.corda.net/OS/4.3/1gnp94c]
`

**Comment by scucchiero** [comment]
As an insight, the same example _seems_ to be working in cordapp-template-java.

**Comment by JonathanScialpi** [comment]
Raised this PR to fix this: https://github.com/corda/cordapp-template-kotlin/pull/73

Edit: Looks like someone already tried to add this PR: https://github.com/corda/cordapp-template-kotlin/pull/69
